sudo: required
# services:
#  - docker
branches:
    only:
      - master
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #to prevent google cloud from displaying any user input prompt (like press y or n)
before_install:
  - openssl aes-256-cbc -K $encrypted_4641aa587ea5_key -iv $encrypted_4641aa587ea5_iv -in mac-gcloud-service-account.json.enc -out mac-gcloud-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file mac-gcloud-service-account.json
  - gcloud config set project ftgo-286210
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials ftgo-cluster
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: echo "This should be running tests for continuous integration"
after_success:
  - ./deployment/kubernetes/scripts/kubernetes-deploy-all.sh
  - ./set-env.sh
  - ./deployment/kubernetes/scripts/port-forwards.sh